### ISSUE TITLE
Implement norm on vectors with custom metric

### ISSUE THREAD

**Issue by FrederikLauber** [rustsim/nalgebra#258]
Hello,

it would be great if we could get a norm on the vector with a custom metric.
As a physicist, having the possibility to use a minkowski metric or similar would be very nice.

Thanks in advance

**Comment by sebcrozet** [comment]
Hi!

That would be a great addition. Which metric do you think nalgebra should provide by default ? (Besides the metrics induced by the p-norms.)

**Comment by FrederikLauber** [comment]
I would argue none because most problems will have their very own metric.
Minkowski is used quite a lot in special relativity but if there is no significant speed boost,
I would the user just define its own.

**Comment by sebcrozet** [comment]
I agree we should let the user define its own specific metric. If you want to try implementing this, you may draw some inspiration from the [dot product](https://github.com/sebcrozet/nalgebra/blob/master/src/core/matrix.rs#L888-L898) method. It has the dimensional constraints that you need.
