### ISSUE TITLE
Serde serialization breakage

### ISSUE THREAD

**Issue by jswrenn** [rustsim/nalgebra#320]
This library upgraded to _serde_ 1.0 in #245. However, the @rust-num crates have yet to upgrade to serde 1.0 (this upgrade is tracked by rust-num/num#357). This breaks _serde_ serialization for all nalgebra types that make direct use of @rust-num's container structures, namely [`Complex`](https://docs.rs/num-complex/0.1.42/num_complex/struct.Complex.html), which is used by nalgebra's [`UnitComplex`](http://nalgebra.org/rustdoc/nalgebra/geometry/type.UnitComplex.html), which is used by [`Isometry2`](http://nalgebra.org/rustdoc/nalgebra/geometry/type.Isometry2.html).

(I imagine this may also affect some of _nalgebra_'s dependent crates, like `ncollide` and `nphysics`, too.)

Unfortunately, I don't think there's much that can be done in nalgebra about this other than wait for rust-num/num#357. Since this is a breaking change for @rust-num crates, it will require a major version number bump for _num_, and for a full fix we will need to coordinate an upgrade of nalgebra's dependencies that depend on _num_, namely _alga_.

**Comment by ThomasdenH** [comment]
What is the status here? The PR in *num* has landed and the new version released.

**Comment by sebcrozet** [comment]
This is fixed as we already depend on num 0.2.
I'll add some tests and then close this.

**Comment by ThomasdenH** [comment]
I see. I was hoping this would fix this PR: https://github.com/ThomasdenH/casimir-fdfd/pull/8.

**Comment by ThomasdenH** [comment]
The PR just changes the nalgebra version. Should I open an issue in this repository or ask somewhere else?

**Comment by sebcrozet** [comment]
> Edit: Removing Cargo.lock before the build solved the problem.

 Now that you mention it, you probably had mismatching versions of `rand` on your `Cargo.lock`. So removing `Cargo.lock` or calling `cargo update` was the right thing to do!
