### ISSUE TITLE
Make SVD::solve return an Option insetad of panicking.

### ISSUE THREAD

**Issue by quadrupleslap** [rustsim/nalgebra#358]
In `svd.rs`:

>    /// Returns `None` if the singular vectors `U` and `V` have not been computed.

But it panics, and it actually can't return `None` because it doesn't return an `Option`. I don't know whether the comment or the code needs to change.

**Comment by sebcrozet** [comment]
While this is a breaking change, it is the code that should change to give the user a chance to handle the `None` case. That means `.recompose()` and `.pseudo_inverse()` should return `None` as well.

**Comment by sebcrozet** [comment]
Fixed by #441.
