### ISSUE TITLE
`Matrix4::new_orthographic` doesn't let you make upside-down projections.

### ISSUE THREAD

**Issue by icefoxen** [rustsim/nalgebra#365]
Namely, if you want a projection where +y is down, you do something like... `Matrix4::new_orthographic(0, 1, 1, 0, 1, 0)` (left, right, top, bottom, near, far).  But it panics when you try to do that, saying the top-left corner must be higher than the bottom-left corner.

This isn't really a problem, but is an inconvenience.

**Comment by sebcrozet** [comment]
I agree this is an useless limitation. It will be fixed in the next minor release of nalgebra.
