### ISSUE TITLE
Need to add `alga` crate dependency in order to use `MatrixN::transform_point`

### ISSUE THREAD

**Issue by Jbat1Jumper** [rustsim/nalgebra#372]
While reading the user guide on _Using raw transformation matrices on points and vectors_<sup>[1][1]</sup>, I saw that it mentions the `transform_point` and `transform_vector` methods but doesn't say that in order to use them you must bring the `alga::linear::Transformation` trait to scope. Looking at the source code in the doc and the example<sup>[2][2]</sup> make it clear, but at first it was a little misleading.

I didn't found another way to use those methods that adding the alga crate to my _Cargo.toml_. So I was thinking, would it be a good idea to reexport the `alga::linear::Transformation`? Or is it better to leave it like that and just add a comment in the documentation?

[1]: http://nalgebra.org/cg_recipes/#using-raw-transformation-matrices-on-points-and-vectors
[2]: https://github.com/sebcrozet/nalgebra/blob/master/examples/transform_matrix4.rs

**Comment by sebcrozet** [comment]
I agree the documentation should clarify the fact the `alga::linear::Transformation` trait must be imported.

For now, I'd prefer not to reexport the trait to keep it clear the abstract traits cone from alga.

**Comment by sebcrozet** [comment]
Closing this in favor of https://github.com/sebcrozet/nalgebra.org/issues/6

**Comment by Ralith** [comment]
Would it make sense to wrap these trait methods as inherent methods for convenience?

**Comment by sebcrozet** [comment]
That can be considered if that makes it easier to use, yes.

**Comment by sebcrozet** [comment]
This was fixed by #457. Closing.
