### ISSUE TITLE
Add .renormalize_taylor to Unit for a faster renormalization.

### ISSUE THREAD

**Issue by sebcrozet** [rustsim/nalgebra#376]
Taylor approximation is an efficient way of re-normalizing a value already close to normalized. Providing this would give the user a faster alternative to the current `.renormalize` method. See the original proposal on the [forum](https://discourse.nphysics.org/t/questions-remarks-around-computation-efficiency/243).

**Comment by simonpuchert** [comment]
It seems like you fixed this issue in https://github.com/rustsim/nalgebra/pull/549, but forgot to close it.

Maybe that happened because the "#" is missing in the commit message, it says "Fix 376.".

**Comment by sebcrozet** [comment]
Ah, you're right. Thank you for noticing this @simonpuchert!
