### ISSUE TITLE
Add a method to create a matrix of vector from a Vec.

### ISSUE THREAD

**Issue by sebcrozet** [rustsim/nalgebra#378]
For dynamically-sized matrices and vectors, this would be much more efficient than the current solutions (`::from_row_slice` and `::from_column_slice`) which copy the content of a slice. See the suggestion on the 5th point of this [post](https://discourse.nphysics.org/t/questions-remarks-around-computation-efficiency/243).

**Comment by sebcrozet** [comment]
Note that the current way of doing this is quite complicated: `DMatrix::from_data(MatrixVec::new(Dynamic::new(nrows), Dynamic::new(ncols), vec))` where `nrows, ncols, vec` are the dimension of the matrix and the Vec.

**Comment by mpizenberg** [comment]
Oh good to know there is a way to do it! I never looked into `MatrixVec` internals yet.

**Comment by sebcrozet** [comment]
Fixed by #464.
