### ISSUE TITLE
partial_clamp unintuitive/broken

### ISSUE THREAD

**Issue by futile** [rustsim/nalgebra#401]
This is using nalgebra version `0.16.3`.

The following code:

```rust
println!("acc: {:?}", acc);
println!("movement.vel: {:?}", movement.vel);
println!("&(movement.vel + acc): {:?}", &(movement.vel + acc));
println!("&movement.max_vel: {:?}", &movement.max_vel);
println!("&-movement.max_vel: {:?}", &-movement.max_vel);

let n = &(movement.vel + acc);
let min = &-movement.max_vel;
let max = &movement.max_vel;
let inter = na::partial_clamp(n, min, max);

println!("inter: {:?}", inter);
```

Produces the following output:

```
acc: Matrix { data: [1.5, 0.0] }
movement.vel: Matrix { data: [0.0, 0.0] }
&(movement.vel + acc): Matrix { data: [1.5, 0.0] }
&movement.max_vel: Matrix { data: [75.0, 0.0] }
&-movement.max_vel: Matrix { data: [-75.0, -0.0] }
inter: None
```

So somehow `[1.5, 0.0]` can not be clamped between `[-75.0, -0.0]` and `[75.0, 0.0]`.

This used to work in a previous version of nalgebra (`0.8.2`) (I am updating some old code), so I suppose this is either intended (and just unintuitive), or broke somewhere along the way.

Thanks!

**Edit:**

Tackling this a bit further, the following worked just fine:

```rust
let inter_x = na::partial_clamp(&n.x, &min.x, &max.x);
let inter_y = na::partial_clamp(&n.y, &min.y, &max.y);

println!("inter_x: {:?}", inter_x);
println!("inter_y: {:?}", inter_y);
```

prints:

```
inter_x: Some(1.5)
inter_y: Some(0.0)
```

Maybe that helps (or maybe I'm just missing something obvious here).

**Comment by sebcrozet** [comment]
Yes, it appears to be a bug. It will be fixed by #404.
