### ISSUE TITLE
Compiler crashes on latest Rust nightly

### ISSUE THREAD

**Issue by timvisee** [rustsim/nalgebra#450]
Compiling `nalgebra` seems to crash the latest Rust nightly compiler with an `internal compiler error`.

I've submitted an issue on the `rust` project regarding this issue: https://github.com/rust-lang/rust/issues/55183

**Comment by vadixidav** [comment]
Confirming that I also get the internal compiler error.

**Comment by timvisee** [comment]
This has been fixed in the latest Rust nightly, thus I will close this issue now.
