### ISSUE TITLE
Storage types are inconsistently named.

### ISSUE THREAD

**Issue by jswrenn** [rustsim/nalgebra#470]
The `Storage` trait is implemented for four types:
 1. `SliceStorage`
 2. `SliceStorageMut` 
 3. `MatrixArray`
 4. `MatrixVec`.

These names are natural to me now, but they weren't when I first started using the library.

`MatrixArray` and `MatrixVec` are easily confusable with the myriad of other `Matrix` types. If you search for `Matrix` in the documentation, you're presented with a pretty overwhelming collection of types with `Matrix` in their name. 90% of them are just aliases of `Matrix`. The exceptions, of course, are `MatrixVec` and `MatrixArray`. Trying to do linear algebra operations directly on these types ends in misery.

A savvy user might then conclude "Oh, if I see `Matrix` followed by a datatype, it's actually an underlying storage type." This rule-of-thumb works well enough, but again there are types that confound this pattern: `MatrixSlice` and `MatrixSliceMut` which _are_ aliases for `Matrix`.

Perhaps a more consistent set of names for the Storage types would be:
 1. `SliceStorage`
 2. `SliceStorageMut` 
 3. `ArrayStorage`
 4. `VecStorage`

**Comment by sebcrozet** [comment]
I strongly agree with you @jswrenn! The current names can be confusing and the ones you propose are good ones.

**Comment by sebcrozet** [comment]
THis was fixed by #496. Closing.
