### ISSUE TITLE
Strides may introduce multiple, aliased mutable pointers.

### ISSUE THREAD

**Issue by jswrenn** [rustsim/nalgebra#486]
For instance:
```rust
use std::ptr;
use std::ops::IndexMut;

let data = &mut [1, 2];

let mut matrix =
  MatrixSliceMut1x2::from_slice_with_strides_mut(data, 0, 0);

assert_eq!(matrix[(0, 0)], matrix[(0, 1)]);
```
The code above is not, on its own, unsafe, but nalgebra relies on many functions with the invariant that strides will not result in aliased elements (e.g., [`matrixmultiply::dgemm`](https://docs.rs/matrixmultiply/0.2.0/matrixmultiply/fn.dgemm.html)).

This problem was noted in #473, but I'm creating a separate issue for visibility since this is a memory safety issue.

**Comment by sebcrozet** [comment]
We should panic when a 0 stride is passed for mutable slices.

**Comment by bluss** [comment]
@jswrenn dgemm will fire a debug assertion for zero strides, but it doesn't catch other cases of cases of course.

**Comment by bluss** [comment]
Oh and by other cases I mean strides that are positive, nonzero and still lead to elements having more than one index that reaches them.

Such strides are most likely a soundness problem for nalgebra IterMuts, if these matrices have them.
