### ISSUE TITLE
Rotation3 no longer has rotate method?

### ISSUE THREAD

**Issue by peterbraden** [rustsim/nalgebra#519]
I get: `no method named `rotate` found for type `na::Rotation<f64, na::U3>` in the current scope`

I'm using code from a former versions documentation. Did this change somehow? I can't find it in the changelog.

**Comment by peterbraden** [comment]
Additionally, when using `*` as in this documentation:

https://docs.rs/nalgebra/0.16.13/nalgebra/geometry/type.Rotation3.html

I get `the trait na::constraint::DimEq<na::U1, na::U3> is not implemented for na::constraint::ShapeConstraint`

**Comment by sebcrozet** [comment]
Yes there is no `rotate` any more since this is covered by operator overloading.

The error you are getting suggests you are multiplying with the vector on the left-hand-side of the operator or multiplying with a row- vector. Is there any code you can show to help understand the operation you are doing ?

**Comment by peterbraden** [comment]
I'm just trying to use a Rotate3 on a Vector3 - Both are row matrices I guess? Surely I should be able to rotate a vector without reshaping a matrix?

The relevant lines: 

```rust
let rotation = Rotation3::new(rotate);
let positions: Arc<Vec<Vector3<f64>>> = Arc::new(                               
                  mesh.positions                                                              
                      .chunks(3)                                                              
                      .map(|i| Vector3::new(i[0] as f64, i[1] as f64, i[2] as f64))          
                      .map(|i| rotate * i)                                          
                      .collect()                                                              
              );
```
( Full source https://github.com/peterbraden/rays.rust/blob/transform-mesh/src/shapes/mesh.rs )

**Comment by peterbraden** [comment]
Oh man, I'm an idiot! Literally spent hours looking in the wrong place. Thanks!
