### ISSUE TITLE
Implement convolution.

### ISSUE THREAD

**Issue by sebcrozet** [rustsim/nalgebra#520]
This has been suggested on the [forum](https://discourse.nphysics.org/t/convolutions-in-nalgebra/299), taking the [convolve](https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.convolve.html) function from scipy as reference.

**Comment by npapapietro** [comment]
Does the fft method required for this? Is direct sufficient based on nalgebra's applications?

**Comment by sebcrozet** [comment]
@npapapietro An implementation based on the FFT would be the best, but a direct method would be good too for a first implementation. It's always better to have the feature even if it's slow, than not having the feature at all!

**Comment by sebcrozet** [comment]
Fixed by #539.
