### ISSUE TITLE
Quaternion * Vector3 does not return expected result

### ISSUE THREAD

**Issue by JensMetzner** [rustsim/nalgebra#540]
The [quat_rotate_vec3](https://github.com/rustsim/nalgebra/blob/fac709b0c0cae8661fc5ecbcc0a803b7bb90a907/nalgebra-glm/src/gtx/quaternion.rs#L47) returns a different result compared to the [C++ glm library's mutliplication](https://github.com/g-truc/glm/blob/fe83040cbda978ad6eb4c94c456e93f35dca88b7/glm/detail/type_quat.inl#L324) between an `Quaternion` and `Vector3`

#### C++:
```C++
std::cout << glm::to_string(orientation);
// output: quat(0.979733, {0.137971, -0.143794, -0.020250})
std::cout << glm::normalize(glm::vec3(0, 0, -1) * orientation));
// output glm::vec3(-0.276172, -0.276172, -0.920575)
```

#### Rust:
```Rust
println!("{:?}",  orientation);
// output: Quaternion { coords: Matrix { data: [0.13797063, -0.14379433, -0.020249786, 0.9797333] } }
println!("{:?}",  normalize(&quat_rotate_vec3(
    &orientation,
    &Vec3::new(0.0, 0.0, -1.0),
)));
// output: Matrix { data: [0.28734794, 0.2645252, -0.9205746] }
```

First of all, is this the right function and if yes, how do the different results come about?

**Comment by sebcrozet** [comment]
Hi!

The two operations you are comparing are not the same. The multiplication `glm::vec3(0, 0, -1) * orientation` has the vector on the left, so I guess C++ glm translates that as applying the inverse of `orientation` to `(0, 0, -1)`. For both operations to be the same you should either change the C++ code to `glm::normalize(orientation * glm::vec3(0, 0, -1)))` or the Rust code to: `normalize(&quat_rotate_vec3(&quat_inverse(&orientation), &Vec3::new(0.0, 0.0, -1.0)))`

**Comment by JensMetzner** [comment]
Thank you very much. This is absolutley right. i missed the `inverse` function.
