### ISSUE TITLE
Why there isn't Matrix4x4?

### ISSUE THREAD

**Issue by clouds56** [rustsim/nalgebra#564]
Others in Matrix4x1 to Matrix4x6 are present.

**Comment by sebcrozet** [comment]
Hi! The 4x4 matrix is called `Matrix4`.

**Comment by clouds56** [comment]
Thanks!
I found it just now, while I'm wondering if there is any reason not to alias Matrix4x4 to Matrix4?
I'm new to the crates and almost create the alias myself.
But fine, to me Matrix4 is Ok, so I just close the issue now.
