### ISSUE TITLE
Documentation typo for nalgebra::base::Vector

### ISSUE THREAD

**Issue by VanillaBrooks** [rustsim/nalgebra#565]
The docs for the axpy method are:
https://github.com/rustsim/nalgebra/blob/d6b5c7f8f7d088baac39d63daa876e0d3ea34cce/src/base/blas.rs#L379-L391

I believe line 381 should be " if `b` is zero `self` is never read from" instead of `be`

**Comment by KappaDistributive** [comment]
This has been fixed in the current master branch.

**Comment by VanillaBrooks** [comment]
https://github.com/rustsim/nalgebra/blob/b5f452087e3367b60dfc097078c5862f17bd8dc9/src/base/blas.rs#L495-L509

You are correct. My mistake.
