### ISSUE TITLE
nalgebra-0.18.0: error[E0277]: the trait bound `rand_hc::Hc128Rng: rand_core::SeedableRng` is not satisfied

### ISSUE THREAD

**Issue by russellb23** [rustsim/nalgebra#610]
I have my Cargo.toml: I have nothing special besides the following as dependency. Changing `nalgebra` version to `0.16.0` doesn't through this message. But, I would loose the `ComplexField` type. Any advise?

`[package]
...
...
...

[dependencies]
nalgebra = "0.18.0"
alga = { version = "0.9", default-features = false }`

[Error stack](https://pastebin.com/QY452cx3)

**Comment by sebcrozet** [comment]
Hi! Did you try to run a `cargo update`? There were breaking changes on the rand crate recently that violated semver rules. I believe they have reverted those changes now.

**Comment by russellb23** [comment]
Thanks @sebcrozet . `cargo update` did the job.
