### ISSUE TITLE
`get()` and `get_unchecked()` are not indexed by row and column (contrary to quick reference)

### ISSUE THREAD

**Issue by VanillaBrooks** [rustsim/nalgebra#614]
The quick reference guide [here](https://www.nalgebra.org/quick_reference/) has the following lines:

`.get_unchecked(i, j)`    [unsafe] Component at row i and column j. No bound checking.
`.get_unchecked_mut(i, j)`   [unsafe] Mutable component at row i and column j. No bound checking.

The docs [here](https://docs.rs/nalgebra/0.18.0/nalgebra/base/struct.Matrix.html#method.get_unchecked) have these functions taking one parameter, which makes sense considering this code does not compile: 
```
fn main() {
    let test_mat = na::Matrix3::<u32>::identity();

    unsafe{ 
        test_mat.get_unchecked(0,0);
    }
}
```
error:
```
error[E0061]: this function takes 1 parameter but 2 parameters were supplied
  --> src\main.rs:54:18
   |
54 |         test_mat.get_unchecked(0,0);
   |                  ^^^^^^^^^^^^^ expected 1 parameter

error: aborting due to previous error
```

The quick reference should be updated to reflect this.

**Comment by sebcrozet** [comment]
That's right, it now takes a single parameter that can be [several kind of indices](https://github.com/rustsim/nalgebra/pull/490). So for your specific example, it should be `test_mat.get_unchecked((0, 0))`.

Thank you for pointing this out! I've opened an [issue](https://github.com/rustsim/nalgebra.org/issues/23) for this on the nalgebra.org repository.
