### ISSUE TITLE
Inverse variants of projection matrix functions

### ISSUE THREAD

**Issue by LaylConway** [rustsim/nalgebra#626]
This is useful for avoiding floating point error, especially in large game worlds, and better performance.
From Emil Persson's SIGGRAPH 2012 Presentation "Creating Vast Game Worlds":

> You often need to use inverse matrices. Inverting a matrix is often a quite lossy process. It is much more accurate to compute the inverse matrix directly from the same parameters that was used to generate the original matrix. It is usually way faster too.

**Comment by sebcrozet** [comment]
Hi! To what projection matrix functions are you referring exactly?

Right now most methods of the `Projective3` and `Orthographic3` types are implemented in a way that takes their characteristics into account. For example, there is:

- the [unproject_point](https://github.com/rustsim/nalgebra/blob/dev/src/geometry/perspective.rs#L200-L208) method applies the inverse of the projection to a point without computing the inverse matrix explicitly.
- the [inverse](https://github.com/rustsim/nalgebra/blob/dev/src/geometry/perspective.rs#L101-L116) method computes the inverse matrix of the projection using the analytic inverse, in a very similar way as what is described in the talk there: https://youtu.be/XXfJQkiuD2k?t=721

The same applies for all non-projection geometric types like the `Isometry3` which also does things similar to what https://youtu.be/XXfJQkiuD2k?t=721 describes for what he calls "reverse transform".

Is this what you were looking for, or are there other methods you would like implemented?

**Comment by LaylConway** [comment]
Ah, I think these are what I'm looking for, thanks!
