### ISSUE TITLE
nalgebra_glm::cross doesn't use D

### ISSUE THREAD

**Issue by talchas** [rustsim/nalgebra#637]
```rust
pub fn cross<N: Number, D: Dimension>(x: &TVec3<N>, y: &TVec3<N>) -> TVec3<N> {
    x.cross(y)
}
```
It is parameterized on `D`, but doesn't use it at all, so you have to manually specify a Dimension parameter that isn't used.

**Comment by sebcrozet** [comment]
That's an oversight. Would you like to open an PR removing this parameter?
