### ISSUE TITLE
Vector of ones

### ISSUE THREAD

**Issue by mandeep** [rustsim/nalgebra#663]
Just as it's common to have a vector of zeros, it's common to have a vector of ones. I think there should be a constructor for this, e.g. `Vector3::ones()`.

**Comment by sebcrozet** [comment]
Hi! There is no `::ones()` because there is no non-ambiguous way of implementing it for matrices too (whereas `::zeros()` is implemented for both matrices and vectors). Instead, you can do `Vector3::repeat(1.0)`.

**Comment by mandeep** [comment]
Makes sense. Thanks!
