### ISSUE TITLE
some non-mut solve method require StorageMut

### ISSUE THREAD

**Issue by nestordemeure** [rustsim/nalgebra#667]
I noticed that, while the `solve` method of the [LU](https://docs.rs/nalgebra/0.19.0/nalgebra/linalg/struct.LU.html#method.solve) decomposition requires a `Storage` trait on its input, the `solve` method for the [qr](https://docs.rs/nalgebra/0.19.0/nalgebra/linalg/struct.QR.html#method.solve) and [FullPivLU](https://docs.rs/nalgebra/0.19.0/nalgebra/linalg/struct.FullPivLU.html#method.solve) decompositions require [StorageMut](https://docs.rs/nalgebra/0.19.0/nalgebra/base/storage/trait.StorageMut.html) which is a much stronger requirement and implies that they will mutate their input.

It seems like a typo due to code duplication with the `solve_mut` methods.

**Comment by sebcrozet** [comment]
Hi! You are right, the `StorageMut` is unnecessary in those places. Would you like to open a PR that replaces them with the `Storage` trait bound instead?

**Comment by nestordemeure** [comment]
I will send a pull request will the correct trait tomorow.

(By the way, I have not forgotten the Cholesky decomposition : I should be able to work on it this weekend.)

**Comment by sebcrozet** [comment]
Fixed by #671.
