### ISSUE TITLE
From matrix to slice implementation.

### ISSUE THREAD

**Issue by wdanilo** [rustsim/nalgebra#687]
Hi! Could we have `From<&Matrix<N,R,C,S>> for &[N]` implementation in nalgebra? It would allow us to generalize some code easier and I believe there would be no downsides for having such a trait impl :)

**Comment by sebcrozet** [comment]
Hi! This is not possible because of Rust orphan rules. However, we can implement `Into<&[N]> for &Matrix<N, R, C, S>` instead.

**Comment by wdanilo** [comment]
Oh, right. The orphan rules are really restrictive these days :( Thanks for implementing Into!
