### ISSUE TITLE
Build failure (on nightly)

### ISSUE THREAD

**Issue by harrysarson** [rustsim/nalgebra#690]
Hi, 

I have just tried to rebuild a project of mine and `cargo check` failed with
```
error: array lengths can't depend on generic parameters
```

This can be reproduced by cloning the dev branch and running `cargo check`. (It looks to be an issue in the `matrixmultiply` dependancy.

Hope this helps!

**Comment by harrysarson** [comment]
Aha, it requires a nightly compiler to get this issue.

**Comment by feuerste** [comment]
See also https://github.com/bluss/matrixmultiply/issues/50 and https://github.com/rust-lang/rust/issues/67743

**Comment by harrysarson** [comment]
Fixed on:

```
nightly-x86_64-apple-darwin (default)
rustc 1.42.0-nightly (689fca01c 2020-01-17)
```

(maybe earlier nightlies too but this one I tested.)
