### ISSUE TITLE
How to perform in place additions of matrices?

### ISSUE THREAD

**Issue by medakk** [rustsim/nalgebra#709]
How do I add a vector to a row? I'm doing

```rust
v.set_row(i, &(v.row(i) + f));
```
but this seems roundabout. I see a component_div_assign, but not equivalent for addition.

Also, there are functions to add_scalar_mut, but I couldn't find anything to multiply by a scalar in place.

**Comment by sebcrozet** [comment]
Additions, subtractions can be done with operators:

```rust
let mut row_i = v.row_mut(i);
row_i += f; // Add the row.
row_i *= scalar; // Multiply by a scalar.
```

One limitation of Rust though prevents you from doing directly:

```rust
v.row_mut(i) += f; // Won't work.
v.row_mut(i).add_assign(f); // Will work.
```

because `row_mut` does not return a pointer. So the `row_i` let binding is necessary unless you call `add_assign` (which is what the operator overloading is sugar for).

**Comment by medakk** [comment]
Thank you!

> Edit: I've seen the discord conversation just now. It appears the removal of t has been suggested by other contributors too.
What do you mean?

**Comment by sebcrozet** [comment]
Oops, sorry, I mixed up two issues! I did not intend to make this edit here.
