### ISSUE TITLE
Generic function calling symmetric_eigen

### ISSUE THREAD

**Issue by nilgoyette** [rustsim/nalgebra#715]
I tried coding a generic function that call `symmetric_eigen` and order the eigenvalues and eigenvectors. The function must accepts various types, like `Matrix3` and `DMatrix`. I'm unable to get the generic part right. This is the best I could do

    pub fn sorted_eigen<N, D, S>(x: SquareMatrix<N, D, S>) -> (..., ...)
    where
        N: RealField,
        D: DimName + DimSub<U1>,
        S: Storage<N, D, D>,
    {
        let eig = x.symmetric_eigen();
        ... sort and return ...
    }

`DimSub<U1>` helped remove one error, but I'm stuck with 3 more errors, which I'm unable to understand or fix:

    note: the method `symmetric_eigen` exists but the following trait bounds were not satisfied:
      `nalgebra::base::default_allocator::DefaultAllocator : nalgebra::base::allocator::Allocator<N, <D as nalgebra::base::dimension::DimSub<nalgebra::base::dimension::U1>>::Output>`
      `nalgebra::base::default_allocator::DefaultAllocator : nalgebra::base::allocator::Allocator<N, D, D>`
      `nalgebra::base::default_allocator::DefaultAllocator : nalgebra::base::allocator::Allocator<N, D>`

Someone known how to fix this?

**Comment by sebcrozet** [comment]
Hi!

Here, the error message shows what needs to be added to your `where` clause:

```rust
pub fn sorted_eigen<N, D, S>(x: SquareMatrix<N, D, S>) -> (..., ...)
where
    N: RealField,
    D: DimName + DimSub<U1>,
    S: Storage<N, D, D>,
    DefaultAllocator: Allocator<N, <D as DimSub<U1>>::Output> +
                      Allocator<N, D, D> +
                      Allocator<N, D>
{
    let eig = x.symmetric_eigen();
    ... sort and return ...
}
```

**Comment by nilgoyette** [comment]
Oh, damn, it was easy after all. Thanl you!
