### ISSUE TITLE
How to index into an array / get a value?

### ISSUE THREAD

**Issue by David-OConnor** [rustsim/nalgebra#733]
```rust
let z = Vector1::new(2.)```

How do I extract `2.` from this Vector?

**Comment by sebcrozet** [comment]
I guess you found the answer of your question. I will answer anyways in case someone else needs it.
There are two possible approaches:
- You can index the vector: `z[0]`.
- Or you can use the `x` component of the vector: `z.x`.

For matrices indexing takes tuples, e.g., `matrix[(2, 3)]`.

**Comment by awarebayes** [comment]
What type should I use to index a vector?

```
let idx:u32 = 34;
println!("{}", Vector3<f64>::new(0.0, 0.0, 0.0)[idx]) 
```
the type `nalgebra::Matrix<f64, nalgebra::U3, nalgebra::U1, nalgebra::ArrayStorage<f64, nalgebra::U3, nalgebra::U1>>` cannot be indexed by `u32`
the trait `std::ops::Index<u32>` is not implemented for `nalgebra::Matrix<f64, nalgebra::U3, nalgebra::U1, nalgebra::ArrayStorage<f64, nalgebra::U3, nalgebra::U1>>`

**Comment by sebcrozet** [comment]
@awarebayes The same type as most array-like Rust collections: `usize`
