### ISSUE TITLE
Matrix constructors should be constant expressions whenever possible.

### ISSUE THREAD

**Issue by wdanilo** [rustsim/nalgebra#738]
Hi! Currently the following code is rejected, but it should be accepted:

```rust
const DEFAULT_POSITION : Vector3<f32> = Vector3::new(1.0,0.0,0.0);
```

**Comment by sebcrozet** [comment]
Hi!

I'll close this issue because it is a duplicate of #521. This was not possible a year ago because of limitations of const-expression in Rust. Though It has improved a lot since then so we should try again now.
