### ISSUE TITLE
Getting `NaN` after applying inversed perspective projection.

### ISSUE THREAD

**Issue by wdanilo** [rustsim/nalgebra#743]
## Description
Hi! Either there is a bug in nalgebra, or I am making some very basic mental error. I would be thankful for any hints / help here. 
Consider the following code:

```rust
    use nalgebra as n;

    let object_space  = n::Vector4::new(0.0,0.0,0.0,1.0);
    let object_matrix = n::Matrix4::identity().append_translation(&n::Vector3::new(100.0,0.0,0.0));
    let world_space   = object_matrix * object_space;

    let camera_matrix = n::Matrix4::identity().append_translation(&n::Vector3::new(0.0,0.0,100.0));
    let view_matrix   = camera_matrix.try_inverse().unwrap();

    let aspect = 1.0;
    let fov    = 90.0f32.to_radians();
    let near   = 0.0;
    let far    = 100.0;
    let perspective           = n::Perspective3::new(aspect,fov,near,far);
    let projection_matrix     = *perspective.as_matrix();
    let inv_projection_matrix = perspective.inverse();

    // let left   = -100.0;
    // let right  = 100.0;
    // let bottom = -100.0;
    // let top    = 100.0;
    // let near   = 0.0;
    // let far    = 100.0;
    // let orthographic          = n::Orthographic3::new(left,right,bottom,top,near,far);
    // let projection_matrix     = *orthographic.as_matrix();
    // let inv_projection_matrix = orthographic.inverse();

    let eye_space  = view_matrix * world_space;
    let clip_space = projection_matrix * eye_space;
    let eye_space2 = inv_projection_matrix * clip_space;

    println!("---------------------------------");
    println!("object_space: {:?}", object_space);
    println!("world_space: {:?}", world_space);
    println!("eye_space: {:?}", eye_space);
    println!("clip_space: {:?}", clip_space);
    println!("eye_space2: {:?}", eye_space2);
```

I get the following results:
```rust
object_space: Matrix { data: [0.0, 0.0, 0.0, 1.0] }
VM115:11957 world_space: Matrix { data: [100.0, 0.0, 0.0, 1.0] }
VM115:11957 eye_space: Matrix { data: [100.0, 0.0, -100.0, 1.0] }
VM115:11957 clip_space: Matrix { data: [100.0, 0.0, 100.0, 100.0] }
VM115:11957 eye_space2: Matrix { data: [100.0, 0.0, -100.0, NaN] }
```

## Problems
Is this correct behavior that we are getting `NaN` as the value of the `w` parameter after applying the inverse projection to the coordinate in `eye_space`? I believe that the perspective projection is always invertible (at least in case the point is located inside of the frustum, but even if not, I don't see any reason it should not be invertible), and I believe in such an operation we should rather not get any `NaN` value.

It's worth noting that everything works correctly when using the `Orthographic` projection (the commented code) instead.

## Edit
It seems it does not happen if the `near` value is not 0. Is this the correct, desired behavior?

**Comment by sebcrozet** [comment]
Hi!

The projection matrix transforms a frustum to a double-unit cube (NDC coordinates). So its inverse projection matrix transforms points from the double-unit cube to the frustum. By setting `near = 0`, the near-plane of this frustum will collapse to a single point. This means that the whole near-plane of the double-unit cube would have to be mapped to a this single point of the frustum. This proves that this projection matrix is not bijective, so it is not invertible, hence the `NaN` when applying the inverse projection.

The perspective matrix is always invertible except for this kind of corner-cases.

**Comment by wdanilo** [comment]
@sebcrozet that of course makes sense. I am just surprised to get NaN for points which are not laying on the 0 Y-Axis. But if that is desired behavior, I'm closing this issue. Thank you for the reply!
